### ISSUE TITLE
abort error

### ISSUE THREAD

**Issue by coleoguy** [johnathanlo/micRocounter#1]
Add a data check to see if you can read the file if not throw a stop with an error message saying file not found.

**Comment by coleoguy** [comment]
This error seems to at least in some cases be preceded by multiple "unable to establish a connection to R session" warnings. In these cases the file is present in the working directory and the program begins to run but then when we would expect the function to be finishing it throws this warning multiple times and then crashes. This type of crash seems to be associated with large genomes

**Comment by johnathanlo** [comment]
data checks added
