### ISSUE TITLE
help files

### ISSUE THREAD

**Issue by coleoguy** [johnathanlo/micRocounter#3]
Change name in read.fasta.Rd to reflect function name. Also make example code store in a variable so a user can just copy and paste to try it out.

create a folder called inst and store a sample file named example.fasta

at the place that you supply the file name do it like this:
system.file("example.fasta", package = "micRocounter")

**Comment by coleoguy** [comment]
read.fasta help file does not correctly describe the returned object please use the information from the manuscript and apply it to this section of the help file.

**Comment by johnathanlo** [comment]
corrected, please check
