### ISSUE TITLE
some genome cause abort error

### ISSUE THREAD

**Issue by coleoguy** [johnathanlo/micRocounter#5]
In testing on a one-year-old MacBook pro, I find some genome cannot be run. The genome is analyzed and the elapsed time prints to screen followed by an R crash abort error.

Drosophila_albomicans.fna file consistently produces this error

**Comment by johnathanlo** [comment]
fixed temporarily by increasing sequence name memory allocation to 200 bytes. Will look for a more permanent solution. Maybe automatically truncate sequence names after 200 bytes or something.

**Comment by coleoguy** [comment]
If we go the truncation route which might not be bad we need it to throw a flag and print to screen "sequence names have been truncated to 200 characters"

**Comment by johnathanlo** [comment]
implemented the flag and truncated at 100 characters if that's okay. 200 might end up making the resulting r vectors a bit unwieldy

**Comment by coleoguy** [comment]
lets try 150 and see how many hit

**Comment by johnathanlo** [comment]
ran with 15 benchmark genomes, none raised flag, going to commit changes for now
