### ISSUE TITLE
cannot report genome sizes larger than ~4.3 gbp and cannot display output for those files either

### ISSUE THREAD

**Issue by johnathanlo** [johnathanlo/micRocounter#7]
Size of output object is "too close to C stack limit" to be displayed in R. Likewise, because Rcpp only supports long int and not long long, cannot have numbers greater than 4.3 billion.

**Comment by coleoguy** [comment]
so would it be possible to convert this into reporting in Mbp instead of bp would this fix it?

**Comment by johnathanlo** [comment]
changed
